name: unittest

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure local json
      run: >
        cat local_json_template.json |
        sed 's/\$DATABASE\$/yppf/g' |
        sed 's/\$USER\$/root/g' |
        sed 's/\$PASSWORD\$/secret/g' |
        sed 's/\$HOST\$/mysql/g' |
        sed 's/\"use_scheduler\": false/\"use_scheduler\": true/g'>
        local_json.json
          cat local_json.json

    - name: Start containers
      run: |
        docker-compose -f env/docker-compose.yml up -d --build
    
    - name: Check host
      run: |
        docker ps -a
        timeout 30s bash -c "while ! curl -Is localhost:8000; do
                                sleep 3
                                echo 'Failed to fetch web page.'
                              done" ||
        "docker-compose -f env/docker-compose.yml logs && exit 1"

    - name: Test 
      run: |
        docker-compose -f env/docker-compose.yml run yppf python3 manage.py test
